apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-projects-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/ml-projects
