apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-projects-pvc
  namespace: ml-projects
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
