apiVersion: v1
kind: Secret
metadata:
  name: ml-projects-secret
  namespace: ml-projects
type: Opaque
data:
  # Base64 encoded values
  api-key: <base64-encoded-api-key>
  database-url: <base64-encoded-database-url>
